CREATE DATABASE IF NOT EXISTS model_example;

CREATE TABLE movies (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  directed_by VARCHAR(100) NOT NULL,
  release_year VARCHAR(100) NOT NULL
);
